### PR TITLE
Update Euler1.py

### PR DESCRIPTION
**Pull request by Moki00**
Hey Robert! You can accept and recode if you like. This is my first try at a pull request for a friend. I'm so glad you're studying this too!!

### CODE REVIEW

**Comment by dancingCamel** [comment]
Hey Morgan, 
Not going to accept it as I use this in my portfolio. However, thanks for introducing me to how pull requests work! 
Have you done any Project Euler stuff?

**Comment by Moki00** [comment]
ok, I closed it. I've done lots of random things. I will make a video about it all soon. I'm also getting into video and and image editing with my new computer. I love a decent graphics card!

**Comment by dancingCamel** [comment]
That's cool. I've seen you're uploading lots of WC3 videos now. How are you studies going? Congrats on the new job, too! I don't know how you find the time to do everything

**Comment by Moki00** [comment]
I don't either...

I was up late playing videos games one night.
It gave me a headache the next day.
I gotta stop that.

I was working on my house until 9pm last night. I took a shower and went to
bed before 11pm. That's a great feeling.

**Pull request closed without merging**
